In [2]:
import numpy as np

arr =np.arange(1,21).reshape((4,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
odd_int = integer[integer % 2 !=0]
print(odd_int)

NameError: name 'integer' is not defined

In [4]:
arr =np.arange(99,79,-1).reshape((4,5))
print ("array :")
print(arr)
multiples = arr[arr % 3==0]
print("Multiples of 3 :")
print(multiples)

array :
[[99 98 97 96 95]
 [94 93 92 91 90]
 [89 88 87 86 85]
 [84 83 82 81 80]]
Multiples of 3 :
[99 96 93 90 87 84 81]


In [ ]:
A= np.array([[1,2,3], [4,5,6], [7,8,9]])
B =np.array([10,10])
print(A,B)
,

[[1 2 3]
 [4 5 6]
 [7 8 9]] [10 10]


ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [6]:
C =A+B 
print(C)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [9]:
m = np.arange (1,13).reshape((3,4))
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
m_transpose = m.T
m_transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])