In [ ]:
    
import numpy as np



In [3]:
arr1d = np.array([2,3,3,3,3])
print(arr1d,type(arr1d))

[2 3 3 3 3] <class 'numpy.ndarray'>


In [4]:
print(f"dimension of array : {arr1d.ndim}") # ndim : number of dimension 


dimension of array : 1


In [5]:
print(f"shape of array : {arr1d.shape}")

shape of array : (5,)


In [6]:
print(f"Data type  of array : {arr1d.dtype}")

Data type  of array : int64


In [7]:
print(f"size of element in byte  : {arr1d.itemsize}")

size of element in byte  : 8


In [8]:
print(f"number of element in array  : {arr1d.size}")

number of element in array  : 5


In [9]:
arr2d = np.array([[11, 12, 13, 14,15],
                [16, 17, 18, 19, 20],
                [21,22,23,24, 25], 
                [26,27, 28,29,30]
])
print(arr2d,type(arr2d))

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] <class 'numpy.ndarray'>


In [10]:
arr3d = np.array


In [11]:
arr = np.linspace(0,10,5)
print(arr,arr.dtype)


[ 0.   2.5  5.   7.5 10. ] float64


In [ ]:
nuzaxwde2f3 g