In [3]:
import numpy as np 
arr2d = np.array([
    [1,1,2,2,3],
    [22,2,3,3,55]
])
print(arr2d[1,4])

55


In [4]:
arr3d = np.arange(11,35).reshape((2,3,4))
arr3d

array([[[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]],

       [[23, 24, 25, 26],
        [27, 28, 29, 30],
        [31, 32, 33, 34]]])

In [5]:
print(arr3d[1,1,3])

30


In [10]:
arr = np.arange(11,21)
arr
sub_array = arr[2:7]
print(f"Sub array :{sub_array}")

Sub array :[13 14 15 16 17]


In [13]:
sub_array_copy= np.copy(arr[2:7])
sub_array_copy

array([13, 14, 15, 16, 17])

In [14]:
arr2d= np.arange(11,31).reshape((4,5))
arr2d


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
sub_arr2d=arr2d[3:4]
print(sub_arr2d)

[[26 27 28 29 30]]


In [19]:
# Read input
first_name = input()
last_name = input()
intial1 = first_name[0]
intial2 = last_name[0]
print(intial1)
print(intial2)

# Create username (lowercase, no space)
# Create initials (uppercase first letters)



IndexError: string index out of range