In [2]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([1,2,3,1])
print(f"Vector v1 :{v1} and vector v2 ={v2}")
dot_product=np.dot(v1,v2)
print (f"the dot product of v1 and v2 : {dot_product}")


Vector v1 :[1 2 3 1] and vector v2 =[1 2 3 1]
the dot product of v1 and v2 : 15


In [3]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B = np.ones ((3,1), dtype ="int")
B

array([[1],
       [1],
       [1]])

In [6]:
M= np.matmul(A, B)

M

array([[ 6],
       [15]])

M1 = A@B
M1

In [7]:
C = np.array([[3,1],[2,2]])
C

array([[3, 1],
       [2, 2]])

In [8]:
print(type(np.linalg))

<class 'module'>


In [9]:
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from '/opt/anaconda3/lib/python3.13/site-packages/numpy/linalg/__init__.py'>
File:        /opt/anaconda3/lib/python3.13/site-packages/numpy/linalg/__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpoolctl: https://github.com/joblib/threadpoolc

In [2]:
import numpy as np
a = np.array([5,7],[3,4])
a = np.array([[17],[10]])
a
b

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [2]:
import numpy as np
data = np.random.randint(0,2,100)


In [3]:
data


array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1])

In [ ]:
data_mean = np.mean(data)
data_mean


In [4]:
np.unique(data)

array([0, 1])

In [5]:
num = np.random.rand(1000)
num[:10]
num.shape

(1000,)

In [6]:
num_mean =np.mean(num)
print(num_mean)

0.4998675669339398


In [7]:
num_min =np.amin(num)
print(num_min)

0.0004693426287273317


In [8]:
num_max =np.amax(num)
print(num_max)

0.9958771303975619


In [ ]:
# generate the 1000 integer random number between 1 to 6 
import numpy as np
numb = np.random.randint(0,7,1000)
numb

array([2, 6, 1, 4, 2, 2, 5, 2, 0, 2, 2, 6, 5, 3, 3, 4, 1, 0, 5, 2, 4, 3,
       6, 5, 5, 6, 5, 0, 3, 5, 1, 1, 5, 5, 5, 3, 0, 3, 2, 2, 5, 5, 2, 5,
       3, 1, 5, 3, 4, 3, 3, 1, 1, 2, 0, 6, 5, 5, 0, 1, 3, 3, 5, 3, 1, 1,
       3, 4, 5, 3, 1, 3, 2, 6, 6, 5, 5, 0, 2, 1, 6, 4, 3, 1, 6, 5, 1, 3,
       4, 4, 5, 0, 4, 1, 2, 0, 4, 0, 6, 1, 3, 3, 5, 3, 4, 5, 6, 3, 2, 4,
       4, 2, 1, 4, 0, 3, 3, 5, 2, 6, 5, 5, 6, 1, 5, 1, 4, 2, 5, 6, 5, 1,
       6, 6, 1, 1, 2, 5, 5, 1, 4, 1, 3, 4, 2, 4, 3, 2, 1, 6, 4, 5, 5, 5,
       6, 4, 0, 6, 0, 0, 2, 2, 3, 1, 2, 5, 1, 6, 3, 3, 1, 2, 2, 6, 4, 2,
       2, 1, 5, 1, 4, 6, 6, 1, 0, 6, 1, 4, 3, 2, 1, 4, 4, 6, 3, 6, 1, 4,
       2, 3, 6, 5, 5, 0, 5, 3, 5, 0, 2, 6, 1, 5, 1, 5, 4, 0, 1, 2, 0, 6,
       3, 6, 0, 2, 6, 1, 0, 1, 6, 3, 0, 1, 3, 4, 3, 6, 6, 5, 0, 6, 2, 3,
       0, 6, 2, 6, 2, 3, 3, 2, 2, 6, 1, 1, 1, 1, 2, 4, 0, 6, 6, 6, 1, 1,
       5, 2, 2, 6, 4, 4, 5, 6, 0, 6, 3, 2, 2, 3, 4, 6, 4, 6, 1, 6, 4, 5,
       5, 1, 5, 2, 0, 4, 1, 5, 0, 0, 4, 6, 1, 0, 2,

In [4]:
numb_mean = np.mean(numb)
numb_mean

np.float64(3.002)

In [5]:
numb_median = np.median(numb)
numb_median

np.float64(3.0)

In [ ]:
data = np.random.uniform(11,21,(1000,))
for i in range(1,1001):
    mean = np.mean(data[:1])
    print(i, ":",mean)

1 : 16.41614213749673
2 : 16.41614213749673
3 : 16.41614213749673
4 : 16.41614213749673
5 : 16.41614213749673
6 : 16.41614213749673
7 : 16.41614213749673
8 : 16.41614213749673
9 : 16.41614213749673
10 : 16.41614213749673
11 : 16.41614213749673
12 : 16.41614213749673
13 : 16.41614213749673
14 : 16.41614213749673
15 : 16.41614213749673
16 : 16.41614213749673
17 : 16.41614213749673
18 : 16.41614213749673
19 : 16.41614213749673
20 : 16.41614213749673
21 : 16.41614213749673
22 : 16.41614213749673
23 : 16.41614213749673
24 : 16.41614213749673
25 : 16.41614213749673
26 : 16.41614213749673
27 : 16.41614213749673
28 : 16.41614213749673
29 : 16.41614213749673
30 : 16.41614213749673
31 : 16.41614213749673
32 : 16.41614213749673
33 : 16.41614213749673
34 : 16.41614213749673
35 : 16.41614213749673
36 : 16.41614213749673
37 : 16.41614213749673
38 : 16.41614213749673
39 : 16.41614213749673
40 : 16.41614213749673
41 : 16.41614213749673
42 : 16.41614213749673
43 : 16.41614213749673
44 : 16.416142137496