In [2]:
import numpy as np
v1 = np.array([1,2,3,1])
v2 = np.array([1,2,3,1])
print(f"Vector v1 :{v1} and vector v2 ={v2}")
dot_product=np.dot(v1,v2)
print (f"the dot product of v1 and v2 : {dot_product}")


Vector v1 :[1 2 3 1] and vector v2 =[1 2 3 1]
the dot product of v1 and v2 : 15


In [3]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
B = np.ones ((3,1), dtype ="int")
B

array([[1],
       [1],
       [1]])

In [6]:
M= np.matmul(A, B)

M

array([[ 6],
       [15]])

M1 = A@B
M1

In [7]:
C = np.array([[3,1],[2,2]])
C

array([[3, 1],
       [2, 2]])

In [8]:
print(type(np.linalg))

<class 'module'>


In [9]:
np.linalg?

Type:        module
String form: <module 'numpy.linalg' from '/opt/anaconda3/lib/python3.13/site-packages/numpy/linalg/__init__.py'>
File:        /opt/anaconda3/lib/python3.13/site-packages/numpy/linalg/__init__.py
Docstring:  
``numpy.linalg``

The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
low level implementations of standard linear algebra algorithms. Those
libraries may be provided by NumPy itself using C versions of a subset of their
reference implementations but, when possible, highly optimized libraries that
take advantage of specialized processor functionality are preferred. Examples
of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
are multithreaded and processor dependent, environmental variables and external
packages such as threadpoolctl may be needed to control the number of threads
or specify the processor architecture.

- OpenBLAS: https://www.openblas.net/
- threadpoolctl: https://github.com/joblib/threadpoolc

In [2]:
import numpy as np
a = np.array([5,7],[3,4])
a = np.array([[17],[10]])
a
b

TypeError: Field elements must be 2- or 3-tuples, got '3'