## Lab:01

## Comparision of performance with list

In [2]:
%%time
## method 1 for squaring the element of list using loop
N=1000000
list_ = list(range(N)) ## range(start, end, step)
for i in range(N):
    list_[i]=list_[i]*list_[i]



CPU times: total: 344 ms
Wall time: 353 ms


In [3]:
%%time
# method 2 for squaring the element of list using list comprenhsive
N=1000000
list_ = list(range(N))
list_sq = [x*x for x in list_]

CPU times: total: 172 ms
Wall time: 182 ms


In [11]:
# inline fucntion
square = lambda x: x*x
print(square(12))

144


In [5]:
def square(x):
    return x*x

print(square(12))

144


In [12]:
%%time
# method 3 for squaring the element of list using list comprenhsive
N=1000000
list_ = list(range(N))
list_sq = map(lambda x: x*x, list_)

CPU times: total: 31.2 ms
Wall time: 44.5 ms


In [7]:
import numpy as np

## Creating the array from start to end with fix step length  

### Syntax: np.arange(start, end, step)

In [8]:
%%time
N = 1000000
arr = np.arange(0,N,1)
arr = arr*arr

CPU times: total: 0 ns
Wall time: 0 ns


### Practice Problem:
create the list of size 1000000 that stor the odd number only starting from 1 and
cube the each element of list using all four method as discussed and analyse the performace. 

In [23]:
N=5
# odd = [1,3,5,7,9]
odd = list(range(1,2*N,2))
print(type(odd))


<class 'list'>


In [24]:
odd_arr = np.arange(1, 2*N,2)
print(type(odd_arr))

<class 'numpy.ndarray'>


## conversion of python object into numpy n-dim array
Syntax:

np.array(python_object)

In [25]:
mylist = [12,12,11,34,56,78]
my_arr = np.array(mylist)
print(type(my_arr))

<class 'numpy.ndarray'>


In [27]:
set1 = {11,44,55,66,77,88}
arr1 = np.array(set1)
print(type(arr1))

<class 'numpy.ndarray'>


In [28]:
tuple1 = (11,44,55,66,77,88)
arr2 = np.array(tuple1)
print(type(arr2))

<class 'numpy.ndarray'>


### Home work:

List, tuple, set, dictinary, conditionl statement, loops, 
functions, inline function, list comprenhsive, classes

## Lab:02

## High Dimensional Array and n-dim numpy array

In [2]:
import numpy as np

In [4]:
# 1-dim array
# creating arr of multiple of 5 using arange function
arr_5x = np.arange(0,100,5)
print(arr_5x, type(arr_5x))

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] <class 'numpy.ndarray'>


In [18]:
# creating array using given list
arr = np.array([0,5.0,10,15,20,25,30,35,40,45,50])
print(arr, type(arr))

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.] <class 'numpy.ndarray'>


In [20]:
print(arr.dtype)

float64


In [6]:
arr1d = np.array([1,2,3,4])
print(arr1d, type(arr1d))

[1 2 3 4] <class 'numpy.ndarray'>


In [7]:
# for check dimension
print(arr1d.ndim)  # ndim: number of dimension

1


In [9]:
# for find shape of array
print(arr1d.shape)

(4,)


In [10]:
# to find the data type of element of array
print(arr1d.dtype)

int32


In [12]:
# to find the size of the array
print(arr1d.size)

4


#### Practice problem 1:
##### Create the 2-dim array of shape (3,4) having element 1 to 12 and then find number of dimension,shape, size, type, datatype of array.

In [16]:
# creating 2-dim array
arr2d  = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
                  ])

print(arr2d, type(arr2d))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'>


#### Practice problem 2:
##### Create the 3-dim array of shape (2,3,4) having element 1 to 24 and then find number of dimension,shape, size, type, datatype of array.

In [17]:
arr3d = np.array([
                    [
                        [1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12],
                    ],
                    [
                        [13,14,15,16],
                        [17,18,19,20],
                        [21,22,23,24]
                    ]
            
                ])

print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [21]:
arr3d[1,2,1]

22